{
 "title": "Sourdough Montoring",
 "description": "ESP32",
 "time": { "from": "2023-12-30T16:49:50.384Z", "to": "2023-12-31T12:40:40.503Z" },
 "templating": {
  "list": [
   {
    "name": "selected_device",
    "label": "Device",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"device\",\r\n  measurement: \"rise\",\r\n  start: -2d,\r\n  stop: now()\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Growth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"rise\")\r\n  |> filter(fn: (r) => r.device == \"$selected_device\")\r\n  |> filter(fn: (r) => r._field == \"height\" or r._field == \"height_std\" or r._field == \"start_calib\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    std_plus: r.height + r.height_std / 6.7 / r.start_calib * 100.0,\r\n    val: r.height,\r\n    std_minus: r.height - r.height_std / 6.7 / r.start_calib * 100.0\r\n   }))\r\n"
    }
   ]
  },
  {
   "title": "Growth Forecast",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "growth_forecast:predicted" },
    { "expr": "growth_forecast:actual" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"rise\")\r\n  |> filter(fn: (r) => r._field == \"temp_in\" or r._field == \"temp_out\")\r\n  |> filter(fn: (r) => r.device == \"$selected_device\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    Inside: r.temp_in,\r\n    Environment: r.temp_out\r\n    }))"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rise\")\n  |> filter(fn: (r) => r._field == \"temp_in\")\n  |> filter(fn: (r) => r.device == \"$selected_device\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Growth / Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"rise\")\r\n  |> filter(fn: (r) => r.device == \"$selected_device\")\r\n  |> filter(fn: (r) => r._field == \"temp_in\" or r._field == \"height\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    Temperature: r.temp_in,\r\n    Growth: r.height\r\n    }))"
    }
   ]
  },
  {
   "title": "Wi-Fi Power",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"rise\")\r\n  |> filter(fn: (r) => r.device == \"$selected_device\")\r\n  |> filter(fn: (r) => r._field == \"wifi_rssi\")\r\n"
    }
   ]
  },
  {
   "title": "Battery level",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"rise\")\r\n  |> filter(fn: (r) => r.device == \"$selected_device\")\r\n  |> filter(fn: (r) => r._field == \"battery_level\")"
    }
   ]
  }
 ]
}